from pathlib import Path

DOSSIER_CVS = Path("cvs")
DOSSIER_CHROMA = "./chroma_db"
FICHIER_MEMOIRE = Path("memoire/memoire.json")
DOSSIER_RESULTATS = Path("resultats")
DOSSIER_OFFRES_DETECTEES = DOSSIER_RESULTATS / "offres_detectees"
DOSSIER_NOTES_AGENT = DOSSIER_RESULTATS / "notes_agent"
FICHIER_OFFRES_DETECTEES = DOSSIER_RESULTATS / "offres_detectees.txt"
FICHIER_NOTIFICATIONS = DOSSIER_RESULTATS / "notifications.log"

MODELE_LLM = "qwen2.5:1.5b"
URL_OLLAMA = "http://localhost:11434"
MODELE_EMBEDDING = "all-MiniLM-L6-v2"

CHUNK_SIZE = 350
CHUNK_OVERLAP = 80
NB_CHUNKS_RAG = 6
NB_CHUNKS_ANALYSE_LLM = 5
DESCRIPTION_MAX_CHARS_REQUETE = 1800
NB_SEGMENTS_DESCRIPTION = 3

SEUIL_SIMILARITE = 0.36

SEUIL_DETECTION = 0.52

PONDERATION_SCORE_RAG = 0.60
PONDERATION_SCORE_LLM = 0.40

SEUIL_COUVERTURE_TITRE = 0.20
SEUIL_COUVERTURE_COMPETENCES = 0.22
SEUIL_COUVERTURE_DOMAINE = 0.18
SEUIL_SUPPORT_CHUNKS = 0.25

FT_CLIENT_ID = "votre_client_id_ici"
FT_CLIENT_SECRET = "votre_client_secret_ici"

URL_TOKEN_FT = "https://entreprise.francetravail.fr/connexion/oauth2/access_token"
URL_OFFRES_FT = "https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search"

MOTS_CLES_DEFAUT = "data scientist"
DEPARTEMENT_DEFAUT = "69"
NB_OFFRES = 5

SURVEILLANCE_ACTIVE = True
INTERVALLE_SURVEILLANCE = 60
INCLURE_OFFRES_MANUELLES = True
OUVRIR_URL_AUTOMATIQUEMENT = False

DECISION_ACCEPTE = "ACCEPTÉ"
DECISION_REFUSE = "REFUSÉ"
DECISION_NSP = "JE NE SAIS PAS"
